In [ ]:
import numpy as np
years_of_esperience = np.array([1,2,3,4])
years_of_esperience_plus_one = years_of_esperience + 1
years_of_esperience_plus_one

array([2, 3, 4, 5])

In [ ]:
years_of_esperience_minus_one = years_of_esperience - 1
years_of_esperience_minus_one

array([0, 1, 2, 3])

In [ ]:
years_of_esperience_half = years_of_esperience / 2
years_of_esperience_half

array([0.5, 1. , 1.5, 2. ])

In [ ]:
years_of_esperience_double = years_of_esperience * 2
years_of_esperience_double

array([2, 4, 6, 8])

In [ ]:
second_and_third_jobs_experience = years_of_esperience[0:3]
second_and_third_jobs_experience

array([1, 2, 3])

In [ ]:
jobs_with_more_than_two_years = years_of_esperience[years_of_esperience > 2]
jobs_with_more_than_two_years

array([3, 4])

In [ ]:
import random

In [ ]:
salary = [random.randint(100000, 150000) for num in range(10)]

In [ ]:
salary

[140796,
 133102,
 127070,
 133818,
 133631,
 141482,
 125782,
 144351,
 110928,
 148251]

In [ ]:
salary_array = np.array(salary)
salary_array

array([140796, 133102, 127070, 133818, 133631, 141482, 125782, 144351,
       110928, 148251])

In [ ]:
total_sum_salaries = np.sum(salary_array)
total_sum_salaries

1339211

In [ ]:
product_salaries = np.prod(salary_array)
product_salaries

-92486958430398464

In [ ]:
cumsum_salaries = np.cumsum(salary_array)
cumsum_salaries

array([ 140796,  273898,  400968,  534786,  668417,  809899,  935681,
       1080032, 1190960, 1339211])

In [ ]:
cumprod_salaries = np.cumprod(salary_array)
cumprod_salaries

array([              140796,          18740229192,     2381320923427440,
        5068954078150788448,  4960030753275755168,  4032982901630103104,
       -8806694175040812672,  2256978377399600768,  2886879796879460352,
         -92486958430398464])

In [ ]:
avarage_salary = np.mean(salary_array)
avarage_salary

133921.1

In [ ]:
median_salary = np.median(salary_array)
median_salary

133724.5

In [ ]:
salary_variance = np.var(salary_array)
salary_variance

106119118.69

In [ ]:
salary_std_dev = np.std(salary_array, ddof=1)
salary_std_dev

10858.64318769973

In [ ]:
min_salary = np.min(salary_array)
min_salary

110928

In [ ]:
max_salary = np.max(salary_array)
max_salary

148251

In [ ]:
salary_with_nan = np.array([123124, np.nan, 145000, 128000, 110000, 149999, np.nan, 135000, 115000, 140000], dtype=float)
salary_with_nan

array([123124.,     nan, 145000., 128000., 110000., 149999.,     nan,
       135000., 115000., 140000.])

In [ ]:
salary_with_nan[salary_with_nan > 130000] = np.nan
salary_with_nan

array([123124.,     nan,     nan, 128000., 110000.,     nan,     nan,
           nan, 115000.,     nan])

In [ ]:
salary_array = np.where(salary_array < 120000, 120000, salary_array)
salary_array

array([140796, 133102, 127070, 133818, 133631, 141482, 125782, 144351,
       120000, 148251])